version: '3.8'

services:
  couchdb:
    image: couchdb
    container_name: couchdb
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin123
    restart: unless-stopped
