version: '3.8'

services:
  arangodb:
    image: arangodb:latest
    container_name: arangodb
    ports:
      - "8529:8529"
    environment:
      - ARANGO_ROOT_PASSWORD=MySecretPass
    volumes:
      - arango_data:/var/lib/arangodb3
    restart: unless-stopped

volumes:
  arango_data:
