version: '3.7'

services:
  # MinIO service
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"   # Expose MinIO web UI
    environment:
      MINIO_ACCESS_KEY: "minio"
      MINIO_SECRET_KEY: "minio123"
    volumes:
      - minio-data:/data   # Persists data between restarts
    command: server /data

  # PostgreSQL service (as an example)
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: exampleuser
      POSTGRES_PASSWORD: examplepassword
      POSTGRES_DB: exampledb
    ports:
      - "5432:5432"  # Expose PostgreSQL to the local machine

  # Redis service (as an example)
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"  # Expose Redis to the local machine

# Named volumes to persist data
volumes:
  minio-data:
