services:
  aws:
    container_name: localstack
    image: localstack/localstack:3.3
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=s3,sqs,sns,dynamodb,lambda,iam,apigateway,cloudformation,sts,secretsmanager,cloudwatch,logs,ecr,route53,events
      - DEBUG=1
      - DATA_DIR=/var/lib/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ./localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - devnet

networks:
  devnet:
    driver: bridge
