version: '3.8'

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"      # API + UI
    environment:
      INFLUXDB_ROOT_TOKEN: my-super-secret-token
      INFLUXDB_ORG: my-org
      INFLUXDB_BUCKET: my-bucket
    volumes:
      - influxdb_data:/var/lib/influxdb2
    restart: unless-stopped

volumes:
  influxdb_data:
